/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { ERC1155Metadata } from "../ERC1155Metadata";

export class ERC1155Metadata__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<ERC1155Metadata> {
    return super.deploy(overrides || {}) as Promise<ERC1155Metadata>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ERC1155Metadata {
    return super.attach(address) as ERC1155Metadata;
  }
  connect(signer: Signer): ERC1155Metadata__factory {
    return super.connect(signer) as ERC1155Metadata__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC1155Metadata {
    return new Contract(address, _abi, signerOrProvider) as ERC1155Metadata;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "_uri",
        type: "string",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
    ],
    name: "URI",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "_interfaceID",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
    ],
    name: "uri",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610346806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806301ffc9a71461003b5780630e89341c14610076575b600080fd5b6100626004803603602081101561005157600080fd5b50356001600160e01b031916610108565b604080519115158252519081900360200190f35b6100936004803603602081101561008c57600080fd5b503561013c565b6040805160208082528351818301528351919283929083019185019080838360005b838110156100cd5781810151838201526020016100b5565b50505050905090810190601f1680156100fa5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b60006001600160e01b031982166303a24d0760e21b141561012b57506001610137565b6101348261021d565b90505b919050565b6060600061014983610236565b60405160200180838054600181600116156101000203166002900480156101a75780601f106101855761010080835404028352918201916101a7565b820191906000526020600020905b815481529060010190602001808311610193575b5050825160208401908083835b602083106101d35780518252601f1990920191602091820191016101b4565b5181516020939093036101000a600019018019909116921691909117905264173539b7b760d91b92019182525060408051808303601a190181526005909201905295945050505050565b6001600160e01b031981166301ffc9a760e01b14919050565b60608161025b57506040805180820190915260018152600360fc1b6020820152610137565b818060005b821561027457600101600a83049250610260565b60608167ffffffffffffffff8111801561028d57600080fd5b506040519080825280601f01601f1916602001820160405280156102b8576020820181803683370190505b50905060001982015b831561030657600a840660300160f81b828280600190039350815181106102e457fe5b60200101906001600160f81b031916908160001a905350600a840493506102c1565b509594505050505056fea2646970667358221220ee4ba4685649f4e0f36c209b8f33d481865aac8473f865bfbaba705ea2d9384964736f6c63430007040033";
