/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { Erc165 } from "./Erc165";

export class Erc165Factory {
  static connect(address: string, signerOrProvider: Signer | Provider): Erc165 {
    return new Contract(address, _abi, signerOrProvider) as Erc165;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "_interfaceID",
        type: "bytes4"
      }
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "pure",
    type: "function"
  }
];
