/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface INiftyswapFactoryInterface extends Interface {
  functions: {
    createExchange: TypedFunctionDescription<{
      encode([_token, _currency, _currencyID]: [
        string,
        string,
        BigNumberish
      ]): string;
    }>;
  };

  events: {
    NewExchange: TypedEventDescription<{
      encodeTopics([token, currency, currencyID, exchange]: [
        string | null,
        string | null,
        BigNumberish | null,
        null
      ]): string[];
    }>;
  };
}

export class INiftyswapFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): INiftyswapFactory;
  attach(addressOrName: string): INiftyswapFactory;
  deployed(): Promise<INiftyswapFactory>;

  on(event: EventFilter | string, listener: Listener): INiftyswapFactory;
  once(event: EventFilter | string, listener: Listener): INiftyswapFactory;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): INiftyswapFactory;
  removeAllListeners(eventName: EventFilter | string): INiftyswapFactory;
  removeListener(eventName: any, listener: Listener): INiftyswapFactory;

  interface: INiftyswapFactoryInterface;

  functions: {
    tokensToExchange(
      _token: string,
      _currency: string,
      _currencyID: BigNumberish
    ): Promise<string>;

    createExchange(
      _token: string,
      _currency: string,
      _currencyID: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  filters: {
    NewExchange(
      token: string | null,
      currency: string | null,
      currencyID: BigNumberish | null,
      exchange: null
    ): EventFilter;
  };

  estimate: {
    createExchange(
      _token: string,
      _currency: string,
      _currencyID: BigNumberish
    ): Promise<BigNumber>;
  };
}
