/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { INiftyswapFactory } from "./INiftyswapFactory";

export class INiftyswapFactoryFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INiftyswapFactory {
    return new Contract(address, _abi, signerOrProvider) as INiftyswapFactory;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address"
      },
      {
        indexed: true,
        internalType: "address",
        name: "currency",
        type: "address"
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "currencyID",
        type: "uint256"
      },
      {
        indexed: false,
        internalType: "address",
        name: "exchange",
        type: "address"
      }
    ],
    name: "NewExchange",
    type: "event"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address"
      },
      {
        internalType: "address",
        name: "_currency",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "_currencyID",
        type: "uint256"
      }
    ],
    name: "createExchange",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address"
      },
      {
        internalType: "address",
        name: "_currency",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "_currencyID",
        type: "uint256"
      }
    ],
    name: "tokensToExchange",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
