/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ReentrancyGuardInterface extends Interface {
  functions: {};

  events: {};
}

export class ReentrancyGuard extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ReentrancyGuard;
  attach(addressOrName: string): ReentrancyGuard;
  deployed(): Promise<ReentrancyGuard>;

  on(event: EventFilter | string, listener: Listener): ReentrancyGuard;
  once(event: EventFilter | string, listener: Listener): ReentrancyGuard;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): ReentrancyGuard;
  removeAllListeners(eventName: EventFilter | string): ReentrancyGuard;
  removeListener(eventName: any, listener: Listener): ReentrancyGuard;

  interface: ReentrancyGuardInterface;

  functions: {};

  filters: {};

  estimate: {};
}
