
on: [push]

name: ci

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - run: yarn install --network-concurrency 1
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}

  lint-ts:
    name: Typescript lint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - run: yarn lint:ts

  size:
    name: Size limit
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - run: yarn build && yarn size

  lint-sol:
    name: Solidity lint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - run: yarn lint:sol

  test:
    name: Test contracts
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - run: yarn start:ganache &
      - run: sleep 10
      - run: yarn test:ganache

  foundry-tests:
    name: Foundry tests
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: FOUNDRY_FUZZ_RUNS=1024 forge test -vvv

  build:
    name: Contracts built
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - run: yarn build
      - run: yarn format:ts
      - run: git diff --exit-code

  # coverage:
  #   name: Coverage
  #   runs-on: ubuntu-latest
  #   needs: [install]
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 18
  #     - uses: actions/cache@master
  #       id: yarn-cache
  #       with:
  #         path: |
  #           node_modules
  #           */*/node_modules
  #         key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
  #     - run: yarn coverage || true
  #     - name: Coveralls
  #       uses: coverallsapp/github-action@master
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
